export const ADD_NEW_TODO_ITEM = "ADD_NEW_TODO_ITEM";
export const MARK_COMPLETE_TODO_ITEM = "MARK_COMPLETE_TODO_ITEM";
export const TOGGLE_TODO_ITEM_IS_CHECKED = "TOGGLE_TODO_ITEM_IS_CHECKED";
export const DELETE_TODO_ITEM = "DELETE_TODO_ITEM";